var pkg = require('./package.json'),
    config = {
        version: pkg.version,
        db: 'mongodb://127.0.0.1/serenader',
        session_secret: 'cute cat',
        port: 10086,
        root_dir: __dirname,
        url: {
            admin: '/admin',
            adminSlug: '/slug',
            adminPost: '/post',
            adminNewPost: '/post/new',
            adminPostUpload: '/public/post_attachment',
            adminCategory: '/category',
            adminNewCategory: '/category/new',
            adminGallery: '/gallery',
            adminNewGallery: '/gallery/new',
            adminGalleryUpload: '/gallery/upload',
            adminGalleryCoverUpload: '/gallery/upload/cover',
            adminFile: '/files',
            adminPublicFile: '/files/public',
            adminPrivateFile: '/files/private',
            adminNewFile: '/files/new',
            adminFileEdit: '/files/edit',
            adminFileMove: '/files/move',
            adminFileCopy: '/files/copy',
            adminFilePreview: '/files/preview',
            adminFileList: '/files/list',
            adminUpload: '/upload',
            adminSetting: '/setting',
            adminUser: '/u',
            adminSign: '/sign',
            adminSignIn: '/signin',
            adminSignUp: '/signup',
            adminSignOut: '/signout',
            indexPost: '/blog',
            indexCategory: '/blog?category=',
            indexTag: '/blog?tag=',
            indexGallery: '/gallery',
            indexAbout: '/about',
            indexUser: '/u',
        },
        assetsUrl: {
            clientSideAssets: '/client',
            serverSideAssets: '/server',
            staticFile: '/static'
        },
        blogConfig: {
            name: 'Serenader',
            desc: 'A blog created by serenader, with some interesting features',
            logo: '/static/logo.png',
            favicon: '/static/favicon.ico',
            allow_sign_up: true,
            theme: 'blue',
            posts_per_page: 10
        },
        dir: [
            '/content/data/private',
            '/content/data/public/background',
            '/content/data/tmp',
            '/content/data/trash'
        ]
    };

module.exports.config = config;
